# Generated by Django 4.0.4 on 2022-05-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='owner',
        ),
    ]
