# Generated by Django 4.0.1 on 2022-05-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_perfil_options_alter_projeto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['created']},
        ),
    ]
