# Generated by Django 4.0.4 on 2022-05-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projetos',
            new_name='Projeto',
        ),
    ]
