# Generated by Django 4.0.4 on 2022-05-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_projetos_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='nome',
        ),
    ]
