# Generated by Django 4.0.4 on 2022-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_projeto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='imagem',
            new_name='imagem_demo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='demo_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
