# Generated by Django 4.0.4 on 2022-05-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.perfil'),
        ),
    ]
