# Generated by Django 4.0.4 on 2022-05-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_projeto_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['created']},
        ),
    ]
