# Generated by Django 4.0.1 on 2022-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=200, null=True)),
                ('sobre_mim', models.TextField(blank=True, null=True)),
                ('imagem_avatar', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('ferramenta1', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('ferramenta2', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('ferramenta3', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('ferramenta4', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('ferramenta5', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
